### ISSUE TITLE
Multiple editors toolbar bug

### ISSUE THREAD

**Issue by jayala** [steveathon/bootstrap-wysiwyg#106]
When you have multiple editors and have text selected in both editors, after pressing a button from the toolbar it applies to both editors not just one.
Steps to reproduce:
1. Open example file examples/multiple-editors.html
2. Write text in first editor and select it
3. Write text in second editor, select it and press one button like "Bold"
4. Text in both editors are afftected, should have effect only in second editor.

**Comment by codewithtyler** [comment]
@jayala Thanks to creating the issue, but this has already been reported in issue #31.

**Comment by jayala** [comment]
Oh, OK! Thank you and sorry for the duplicate.
