### ISSUE TITLE
Bootstrap Version

### ISSUE THREAD

**Issue by periscuelo** [steveathon/bootstrap-wysiwyg#132]
Hi guys. First thanks for your great job.
This wysiwyg Works with bootstrap 4?

Thanks again.

**Comment by spreadred** [comment]
I have only tested it with Bootstrap 3.3.4. The easiest way to get an answer to your question is to try it yourself. Let us know if you encounter any issues.

**Comment by periscuelo** [comment]
I try npm i bootstrap-wysiwyg-4 but have a bower error. As I did not see any bootstrap version information I decided to ask. As possible I try to use and open some issue if it is the case. Thanks for response.

**Comment by spreadred** [comment]
@periscuelo Yes, please create an new issue for this so that we may investigate.

**Comment by periscuelo** [comment]
Ok thanks
