### ISSUE TITLE
Toolbar is not being updated

### ISSUE THREAD

**Issue by akoskm** [steveathon/bootstrap-wysiwyg#19]
In the current master branch the toolbar is not being updated.

To reproduce:

1. open clear-formatting.html
2. write some text
3. select all
4. click B

expected result:
selection is bold and the toolbar button B changes its class to ```btn-info```

what happens:
selection is bold but the toolbar button B remains ```btn-default```

It can be reproduced by starting any html from the examples directory.

**Comment by akoskm** [comment]
The problem is caused by ```underscoreThrottle``` which throttles the bold command and it never gets to the callback function.

**Comment by Findus23** [comment]
Is there already a fix for this issue?
It would be really helpful to be able to detect which button is activated.

**Comment by RandomlyKnighted** [comment]
@Findus23 No, there has not been a fix added for this yet.
