### ISSUE TITLE
Selection is partially broken

### ISSUE THREAD

**Issue by akoskm** [steveathon/bootstrap-wysiwyg#20]
In the current master branch you cannot select text by dragging the mouse in the text area.

This is working with the the older version of this plugin: http://mindmup.github.io/bootstrap-wysiwyg/

**Comment by RandomlyKnighted** [comment]
I'm able to select text, just not able to type anything as every key (no matter what key I press) just turns bold on and off.

**Comment by RandomlyKnighted** [comment]
@akoskm did you include jQuery.hotkeys in your project? Once I added that everything started working for me.

**Comment by RandomlyKnighted** [comment]
@akoskm Were you able to get this to work?

**Comment by akoskm** [comment]
@RandomlyKnighted no, in the mean time I think we just switched to another editor. I'll check and report you back.

**Comment by akoskm** [comment]
@RandomlyKnighted we found no reliable text editors so we implemented a plain textarea/preview editor similar to this comment box.
