### ISSUE TITLE
Is there an "on change" event?

### ISSUE THREAD

**Issue by rashandzamshut** [steveathon/bootstrap-wysiwyg#27]
I need a callback function to run each time html within editor changes - when user types, pastes, cuts, clicks buttons. I tried the obvious code below, but my console didn't log any messages. How do I do this?

    $('#bootstrapWysiwyg').change(function(){
        console.log('CHANGED');//not triggered
    });

    $('#bootstrapWysiwyg').on('change', function(){
        console.log('CHANGED');//not triggered
    });

    $('#bootstrapWysiwyg').wysiwyg();//INSTANTIATING (and it actually works)

    $('#bootstrapWysiwyg').change(function(){
        console.log('CHANGED');//not triggered
    });

    $('#bootstrapWysiwyg').on('change', function(){
        console.log('CHANGED');//not triggered
    });

**Comment by rhpot1991** [comment]
There is a change event you can use:

https://github.com/steveathon/bootstrap-wysiwyg/blob/master/examples/events.html

**Comment by rashandzamshut** [comment]
This seems to be browser specific. In Chrome, instead of "change" I had to use "input". Would be nice if this plugin had some built-in abstraction over this, but for now I think this issue should be closed.
