### ISSUE TITLE
Are there working samples?

### ISSUE THREAD

**Issue by xplicit** [steveathon/bootstrap-wysiwyg#29]
I have installed bootstrap-wysiwyg-steveathon from bower. Then I opened a file `examples/basic.html` and tried to write some chars into edit field. I've got a javascript exception:

    NotFoundError: Node was not found
    document.execCommand(command, 0, args);

browser: firefox 37.0.2

Are there any working samples how to use this component?

**Comment by xplicit** [comment]
Also the site http://steveathon.github.io/bootstrap-wysiwyg/ does not show working samples of component, which can be evaluated on the site. It only links to the page with old mindmup wysiwyg component.

**Comment by RandomlyKnighted** [comment]
There is no current live sample no, all working samples are available from the repo itself. I'm also running Firefox v37.0.2 and I'm able to use basic.html with no problems.

**Comment by xplicit** [comment]
What I do:
open empty folder

`bower install jquery.hotkeys`

add in file `bower_components\jquery.hotkeys\.bower.json` string `"version" : "1.0.0"`

`bower install bootstrap-wysiwyg-steveathon`

navigate to `bower_components\bootstrap-wysiwyg-steveathon\examples`

run `firefox basic.html`

after then I've try to enter some chars into the edit field and have got js error

**Comment by xplicit** [comment]
OK, I've tried to clone repository and from repository basic sample is working, so the issue is only about bower package.

**Comment by RandomlyKnighted** [comment]
Right, I've got a PR open that updates the project's bower.json file (plus adds some other minor stuff that I've caught). I'm using the one in my PR with no problems.

**Comment by steveathon** [comment]
Marked this as a bug because it will be fixed with the bower change.

Confirmed enhancement on #39 to add others on the pages.
