### ISSUE TITLE
bootstrap-wysiwyg.min.js missing a final semicolon; causing cascaded script failures.

### ISSUE THREAD

**Issue by durangosw** [steveathon/bootstrap-wysiwyg#32]
The missing semicolon is causing all following scripts to fail. 

It stands to reason this will also cause problems if sourcing the scripts in a web page, but have only tested the gulp mix.

*Steps to Reproduce*
1.  Create a gulp mix.scripts command.
2.  Prepend bootstrap-wysiwyg.min.js to the array of scripts to combine.
3.  Run gulp.
4.  View importing web page in chrome, and then open chrom dev tools to see errors.

*Workarounds (successful ones are marked with an 'x'):*
- [x] Use the non-minified version, which has the semicolon.
- [ ] Put the minified version last in the list of scripts to mix or load?
- [x] Manually add a semicolon to the minified version.  This is not optimal, esp. if using a package manager.

**Comment by RandomlyKnighted** [comment]
In my current PR #25 I used Gulp to lint and minify the bootstrap-wysiwyg.js file. Once that PR has been merged it should fix your issue.

**Comment by RandomlyKnighted** [comment]
FYI there was multiple missing semicolons.

**Comment by durangosw** [comment]
Thanks in advance!

**Comment by RandomlyKnighted** [comment]
@steveathon this can be closed now
