### ISSUE TITLE
Add live demo

### ISSUE THREAD

**Issue by dandv** [steveathon/bootstrap-wysiwyg#39]
Also requested between the lines in #29.

I'm [comparing a bunch of editors](https://github.com/iDoRecall/comparisons/blob/master/JavaScript-WYSIWYG-editors.md) and a live demo would help.

**Comment by steveathon** [comment]
Agreed. We need to add live demos, we will add them on the gh-pages branch. Likewise, in #29 we'll update those to make them work with the updated bower.

**Comment by RandomlyKnighted** [comment]
This issue can now be closed per PR #54. You can now find the live demo at: http://steveathon.github.io/bootstrap-wysiwyg/

**Comment by dandv** [comment]
Thanks. The demo doesn't work right now though: I can't type anything, and the console shows http://steveathon.github.io/bootstrap-wysiwyg/bower_components/jquery.hotkeys/jquery.hotkeys.js couldn't load.

**Comment by RandomlyKnighted** [comment]
That's right, I forget that Jekyll can't handle using Bower libraries. Unfortunately, there is not a CDN anywhere that hosts jquery.hotkeys so I'm in the process of getting it added to cdnjs.com. My PR is [here](https://github.com/cdnjs/cdnjs/pull/5483). As soon as it gets merged I'll update the site with the link to the new CDN file.

**Comment by dandv** [comment]
JSDelivr might make it [easier](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md) to get the library on its CDN?

**Comment by RandomlyKnighted** [comment]
Thanks @dandv I'll see about getting it added to that as well. If all goes well the demo might be updated sooner than expected.

**Comment by RandomlyKnighted** [comment]
I've added a [PR for JSDelivr](https://github.com/jsdelivr/jsdelivr/pull/6618) as well. Hopefully we'll get things worked out soon and I'll be able to update the site.

**Comment by RandomlyKnighted** [comment]
This has been fixed. It can now be closed.
