### ISSUE TITLE
1.0.3-rc doesn't seem to work

### ISSUE THREAD

**Issue by ehinter** [steveathon/bootstrap-wysiwyg#47]
I downloaded 1.0.3-rc and opened examples/basic.html but nothing happens when I type in the textbox. This happens in all browsers.

**Comment by ehinter** [comment]
(1.0.2 doesn't have this problem)

**Comment by RandomlyKnighted** [comment]
Did you install all the packages using bower? If these packages are not installed then the editor will not work, because it depends on things like jQuery in order to work.

**Comment by ehinter** [comment]
Ok, I guess that's the issue. The 1.0.2.zip included an 'external' directory with the dependencies but I guess 1.0.3-rc doesn't. 

https://github.com/steveathon/bootstrap-wysiwyg/archive/1.0.3-rc.zip
https://github.com/steveathon/bootstrap-wysiwyg/archive/1.0.2.zip

**Comment by RandomlyKnighted** [comment]
Correct, in the latest release we migrated everything over so that it now uses Bower. Now we can just let Bower handle our dependencies rather than having to package them ourselves in each release.
