### ISSUE TITLE
Implementing WYSIWYG in .net

### ISSUE THREAD

**Issue by w0ns88** [steveathon/bootstrap-wysiwyg#55]
Hi,

I am new to this, but I would like to know how to implement the text editor to a .net MVC application?

Thanks in advance.

**Comment by RandomlyKnighted** [comment]
Hi @wons88 you should take a look at [MiniBlog](https://github.com/madskristensen/Miniblog). It's a minimalistic blog engine developing using ASP.NET Web Pages. It should give you an idea how you could implement the editor in ASP.NET.

**Comment by wons88** [comment]
Thanks, I'll check it out.

**Comment by RandomlyKnighted** [comment]
@wons88 did that help you any?

**Comment by steveathon** [comment]
Closing as this seems resolved.
