### ISSUE TITLE
activeToolbarClass only applied to first button.

### ISSUE THREAD

**Issue by andrews05** [steveathon/bootstrap-wysiwyg#58]
As can be seen on the demo page, when using the bold, italics etc only the bold button will ever be highlighted when active.

**Comment by RandomlyKnighted** [comment]
Thanks for creating this issue @andrews05. I noticed this happening the other night when I was testing some things but I thought it was just something on my end. 

Would you like to work on this issue or should I add it to my list of things to do when I get time?

**Comment by andrews05** [comment]
Not sure if I'll be able to be much help, I'm not familiar with the code. All I can work out is its caused by the underscoreThrottle function.

**Comment by RandomlyKnighted** [comment]
That's fine. If it's an issue with underscoreThrottle I'll definitely need to take a look at it soon. I remember there being a report somewhere about that causing another issue as well so it maybe something that we'll need to look into either fixing or replacing it with a custom solution.

**Comment by andrews05** [comment]
Great, thanks for all your work.

**Comment by RandomlyKnighted** [comment]
I think I may have a solution to this problem worked up. I've just got to do some additional testing to make sure I didn't screw anything else up.
