### ISSUE TITLE
Preventing tabulator

### ISSUE THREAD

**Issue by timkley** [steveathon/bootstrap-wysiwyg#59]
Hi,

I have an application where I need to prevent tabulators, my code looks like the following:

    $('#subject').wysiwyg({
        toolbarSelector: '',
        hotKeys: {}
    });

    $('#subject').on('keydown keyup', function(e) {
        if (e.keyCode == 13 || e.keyCode == 9) {
            e.preventDefault();
        }
    });

When hitting `enter` it is being prevented like it should be, but a `tab` doesn't get prevented. Also providing an empty `hotKeys` parameter didn't change anything (in fact: none of the hotkeys get prevented?)

**Comment by RandomlyKnighted** [comment]
I believe this is a bug with jQuery Hotkeys rather than with the editor itself.

**Comment by steveathon** [comment]
Does this happen in all browsers?

**Comment by RandomlyKnighted** [comment]
I know it happens in Chrome, because I was able to replicate it the other day.

**Comment by steveathon** [comment]
Ok great - let's see if we can replicate it in FF and Safari, if so then
we're likely going to need to raise it with that project as they don't
currently have an open issue for it.
