### ISSUE TITLE
How can I save the uploaded image to php server?

### ISSUE THREAD

**Issue by Palazi** [steveathon/bootstrap-wysiwyg#63]
I cant figure out , How I can save the uploaded image to php server

**Comment by RandomlyKnighted** [comment]
You should be able to use a jQuery selector to grab any images that have been added to the editor's div then copy that to the server. Once you get the images selected you just have to copy it to the destination folder on your server. In my senior level independent study I created an upload function that copied files to the server. You can see that function [here](https://github.com/RandomlyKnighted/discourse-analysis/blob/master/src/fileModule.php#L14).

**Comment by steveathon** [comment]
There is a php example here: https://github.com/steveathon/bootstrap-wysiwyg/blob/master/examples/form-post.html and https://github.com/steveathon/bootstrap-wysiwyg/blob/master/examples/php/upload.php

Elements submit as post variables and you can then just decode them and store them. You can also further manipulate them using the PHP image libraries, if you wanted to.

**Comment by steveathon** [comment]
I'm going to close this as it's not a request, so to speak. Please feel free to add more comments if you still need some help.
