### ISSUE TITLE
Can't use the Hyperlink button in Chrome on Mac

### ISSUE THREAD

**Issue by soitgoes** [steveathon/bootstrap-wysiwyg#7]
Hyper link dialog closes as soon as typing starts.

**Comment by ducnvhn** [comment]
same problem. I click on the add link btn and the drop-down appear but it will close as soon as I click on the input box to add link. any same issue ?

**Comment by benwurth** [comment]
I've got the same issue. Any ideas for workarounds?

**Comment by RandomlyKnighted** [comment]
If you've setup your hyperlink button like in the examples then add the following script to your file to get it to work again. I'm adding it to my PR now so this will be fixed when my PR has been merged.

```javascript
$(".dropdown-menu > input").click(function (e) {
        e.stopPropagation();
});
```
