### ISSUE TITLE
createLink not working in Firefox 42 on Mac OS 10.11.1

### ISSUE THREAD

**Issue by tbhockey** [steveathon/bootstrap-wysiwyg#74]
The example `createLink` code, while working correctly in all other browsers I've tested, does nothing in Firefox 42.

```
<div class="btn-group">
	<a class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="fa fa-link"></i></a>
	<div class="dropdown-menu input-append">
		<input placeholder="URL" type="text" data-edit="createLink" />
		<button class="btn" type="button">Add</button>
	</div>
</div>
```

In FF, the toolbar closes upon clicking the "Add" button, but the value of the input doesn't go anywhere. Anyone else run into this? I was actually developing in FF and couldn't get this "working" for hours, then realized that it had been working all along in other browsers.

**Comment by RandomlyKnighted** [comment]
That's odd that you only have this issue with Firefox. When I originally found this bug it was happening in all browsers. If you'll look at the example html files you'll see the following JavaScript is added to each example:

```javascript
$(".dropdown-menu > input").click(function (e) {
    e.stopPropagation();
});
```

This fixes the issue you mentioned.

**Comment by tbhockey** [comment]
Hi Tyler, thanks for the response. I had actually implemented that JS already and it doesn't seem to make any difference; at least not in FF 42, which is the only one I have access to at the moment.

**Comment by RandomlyKnighted** [comment]
Alright, I'll check it out again this afternoon. Firefox made have changed something in one of their last updates.

**Comment by tbhockey** [comment]
Thanks @RandomlyKnighted . FYI I was just able to run some testing in other versions. Had the same problem down to FF 41. At FF 38 and below it works perfectly fine. I'll see if I can figure out the exact version where it breaks.

**Comment by tbhockey** [comment]
Ah... please ignore that ^ comment. Not working for me in *any* FF version actually...

**Comment by tbhockey** [comment]
I know this project has been modified from the MindMup one, but I have the exact same problem in FF on their example at: http://mindmup.github.io/bootstrap-wysiwyg/

**Comment by RandomlyKnighted** [comment]
That's odd I just tested using that link and I had no issues. I tested it using Firefox 42. 

Just to be clar when you type in ```http://www.google.com``` in the textbox and click Add it does not turn the word that you highlighted blue nor does it underline the word?

**Comment by tbhockey** [comment]
That is correct. Here's a screen capture: https://dl.dropboxusercontent.com/u/1224683/ff.mov

**Comment by RandomlyKnighted** [comment]
In that video you didn't highlight any text first. So it doesn't have anywhere to put the link. Try highlighting the word ahead and then use the createLink button. It works just like the createLink button in Microsoft Outlook. The word has to be highlighted (or selected) in order to add the link to it.

**Comment by tbhockey** [comment]
DOH! :anguished: I had no idea that was how it is designed to work! Yes, it works perfectly fine like that. In every other browser you can just create at link w/o highlighting any other text, which is what led me to believe that's how it works. Well than you so much for clarifying!

**Comment by RandomlyKnighted** [comment]
No problem.
