### ISSUE TITLE
Minor fix: Bower.json path to main file is incorrect

### ISSUE THREAD

**Issue by arjshiv** [steveathon/bootstrap-wysiwyg#76]
Currently, ```bower.json``` points to its main files in the following way

```javascript
  "main": [
    "bootstrap-wysiwyg.js",
    "bootstrap-wysiwyg.min.js"
  ],
```

This fails in automated injection of bower dependencies into my code using require/WebPack since they read from this file to know which files to inject, since the files are actually in the ```js``` and ```src``` folders (and ```src``` is not installed when using ```bower install```)

This can easily be fixed by changing to the following (if you do not want to install src):

```javascript
"main": [
    "js/bootstrap-wysiwyg.min.js"
  ],
```

Let me know if this makes sense, I'm happy to make the change. Another potential workaround is by using my bower.json to override the main files, but that still doesn't resolve the issue for all injection systems and it's a pretty simple fix.

**Comment by arjshiv** [comment]
The same goes for the CSS file as well.

Additionally, adding a license field would be helpful per bower spec.

**Comment by Findus23** [comment]
While we're on it: Can we update font-awesome to 4.5.0?

**Comment by arjshiv** [comment]
I've put in a pull request for this. Please review and let me know if I can help further. This library if pretty awesome! Thanks :)

**Comment by RandomlyKnighted** [comment]
@Findus23 why not just update your PR for 4.4.0 to go to 4.5.0.

**Comment by Findus23** [comment]
Sorry, my fault. I forgot that I had mentioned it before. 
I'll change it.

**Comment by arjshiv** [comment]
Thanks for the merge. Closing this issue now.
