### ISSUE TITLE
Adding support for Font Awesome 4.2

### ISSUE THREAD

**Issue by steveathon** [steveathon/bootstrap-wysiwyg#8]
I'm adding support for Font-Awesome 4.2. This is a pretty straight forward change but it does break 3.x support because of the change in tags.

**Comment by RandomlyKnighted** [comment]
#22 adds support (to all HTML files) for Font Awesome 4.3.0. I took the liberty of updating all the tags so that it doesn't break the page.

**Comment by RandomlyKnighted** [comment]
@steveathon is there anything else I can do to to finish up this issue?
