### ISSUE TITLE
CSS style for image upload  has some problem

### ISSUE THREAD

**Issue by billzt** [steveathon/bootstrap-wysiwyg#86]
The original CSS style has problems.
`.imgUpload
{
	width: 10;
	height: 10;
	position:absolute
}`

I can't click the upload button. It didn't do anything.

However, if I change to this (inspired from http://www.bootcss.com/p/bootstrap-wysiwyg/), it works.

`.imgUpload
{
	opacity: 0; 
    position: absolute; 
    top: 0px; 
    left: 0px; 
    width: 41px; 
    height: 30px;
}`

**Comment by RandomlyKnighted** [comment]
Which examples file are you looking at?

**Comment by billzt** [comment]
@RandomlyKnighted example file: form-post.html

**Comment by RandomlyKnighted** [comment]
Ah I see what you're talking about now. PR #68 fixes this issue.

**Comment by billzt** [comment]
OK.
