### ISSUE TITLE
This is not working!?

### ISSUE THREAD

**Issue by blaasvaer** [steveathon/bootstrap-wysiwyg#95]
When I start typing in the editor, all the buttons start hiliting on and off, but no characters get typed into the editor. I also tried running it from localhost server, to see if that helped – same thing.

Tested in FireFox 46.0.1 and 50.0.2661.94 (64-bit).

**Comment by RandomlyKnighted** [comment]
@blaasvaer Thanks for reporting this issue. If you could answer the few questions below it would help me get an idea what might be causing this problem. Thanks!

1. What file are you looking at when this issue occurs?
2. Did you install all bower and npm dependencies before attempting to test the editor?

**Comment by mcshiz** [comment]
I was having the same issue, make sure you update your dependencies.

In my case once I updated jquery.hotkeys everything worked again

The syntax might be broken in the bower.json file. Instead of putting the path to the repo can you put a version number?

**Comment by codewithtyler** [comment]
A version number will not work because there is no Bower package for jQuery Hotkeys.

**Comment by mcshiz** [comment]
I guess there is a jquery.hotkeys bower package but it's the wrong repo and it's not compatible with this project. So it either needs to be removed from the bower.json or something because it's pulling in the wrong library.

**Comment by codewithtyler** [comment]
@mcshiz I just deleted my bower_components folder, did a bower install and it downloaded the correct file from GitHub.

Edit: The bower package you're seeing is the original jQuery Hotkeys. However, John Resig forked the project a while back and his fork is now considered the most recent version.

**Comment by blaasvaer** [comment]
Yup, fixed the problem. Thanks.
